# Generated by Django 4.0.2 on 2022-08-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Photo', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('OfficePhone', models.IntegerField(blank=True, null=True)),
                ('HomeAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('WorkAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('AdharCard', models.CharField(blank=True, max_length=100, null=True)),
                ('Pancard', models.CharField(blank=True, max_length=100, null=True)),
                ('Passport', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('WorkEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('AboutMe', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('JoiningDate', models.DateTimeField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('EMPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
