# Generated by Django 4.0.2 on 2022-08-21 03:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyEmergencyContacts',
            fields=[
                ('relationshipId', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100)),
                ('contactNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTotalLeaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[('CasualLeave', 'CasualLeave'), ('SickLeave', 'SickLeave')], max_length=100)),
                ('TotalleaveCount', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 40, 18, 96899))),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(choices=[('CasualLeave', 'CasualLeave'), ('SickLeave', 'SickLeave')], max_length=100)),
                ('leaveCount', models.IntegerField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 40, 18, 96899))),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('leaveType', models.CharField(choices=[('CasualLeave', 'CasualLeave'), ('SickLeave', 'SickLeave')], max_length=100)),
                ('leaveDescription', models.CharField(max_length=100)),
                ('leaveStatus', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('assigne', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLanguageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('proficientLevel', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountType', models.CharField(choices=[('Salary Account', 'Salary Account'), ('PPF Account', 'PPF Account')], max_length=100)),
                ('AccountName', models.CharField(max_length=100)),
                ('IFSCCode', models.CharField(max_length=100)),
                ('BankName', models.CharField(max_length=100)),
                ('AccountNumber', models.IntegerField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Photo', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('OfficePhone', models.IntegerField(blank=True, null=True)),
                ('HomeAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('WorkAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('AdharCard', models.CharField(blank=True, max_length=100, null=True)),
                ('Pancard', models.CharField(blank=True, max_length=100, null=True)),
                ('Passport', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('WorkEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('AboutMe', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('JoiningDate', models.DateTimeField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
