# Generated by Django 4.0.2 on 2022-09-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprojectdetails',
            old_name='duration',
            new_name='Years',
        ),
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 19, 565166)),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='AccountType',
            field=models.CharField(choices=[('SalaryAccount', 'SalaryAccount'), ('PPFAccount', 'PPFAccount')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 19, 564171)),
        ),
        migrations.AlterField(
            model_name='employeeprojectdetails',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 19, 564171)),
        ),
    ]
