# Generated by Django 4.0.2 on 2022-08-29 17:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeIdentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 23, 7, 39, 870769)),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='category',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Salary', 'Salary'), ('Other', 'Other'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeticket',
            name='ticketDescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 23, 7, 39, 871672)),
        ),
        migrations.CreateModel(
            name='EmployeeAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 23, 7, 39, 872745))),
                ('Announcement', models.TextField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
