# Generated by Django 4.0.2 on 2022-08-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EMPID',
            new_name='username',
        ),
    ]
