# Generated by Django 4.0.2 on 2022-08-29 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeapplyleave',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeapplyleave',
            name='leaveCount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeeapplyleave',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 16, 24, 28, 762375)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 16, 24, 28, 762375)),
        ),
    ]
