# Generated by Django 4.0.2 on 2022-08-21 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 55, 15, 958697)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='TotalleaveCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 55, 15, 958697)),
        ),
    ]
