# Generated by Django 4.0.2 on 2022-08-21 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0002_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 58, 12, 215491)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 8, 58, 12, 215491)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='leaveType',
            field=models.CharField(blank=True, choices=[('CasualLeave', 'CasualLeave'), ('SickLeave', 'SickLeave')], max_length=100, null=True),
        ),
    ]
