# Generated by Django 4.0.2 on 2022-08-29 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0002_employeeapplyleave_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeapplyleave',
            name='leaveStatus',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 16, 27, 11, 861949)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 16, 27, 11, 861949)),
        ),
    ]
