# Generated by Django 4.0.2 on 2022-08-30 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeIdentification', '0002_alter_employeecreditleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 11, 58, 45, 892329)),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 11, 58, 45, 891329)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 11, 58, 45, 891329)),
        ),
        migrations.CreateModel(
            name='SkillManagement',
            fields=[
                ('SkillId', models.AutoField(primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=100)),
                ('ProficientLevel', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100)),
                ('Experience', models.FloatField()),
                ('LastUsed', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
