# Generated by Django 4.0.2 on 2022-09-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0002_rename_duration_employeeprojectdetails_years_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprojectdetails',
            old_name='Years',
            new_name='Duration',
        ),
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 50, 181502)),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 50, 180505)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 16, 22, 50, 180505)),
        ),
    ]
