# Generated by Django 4.0.2 on 2022-08-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0002_rename_empid_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='empid',
        ),
    ]
