# Generated by Django 4.0.2 on 2022-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0003_rename_username_employee_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
