# Generated by Django 4.0.2 on 2022-08-28 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0003_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyemergencycontacts',
            old_name='relationship',
            new_name='relationshipName',
        ),
        migrations.AddField(
            model_name='familyemergencycontacts',
            name='relationshipType',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 8, 57, 519347)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 8, 57, 519347)),
        ),
    ]
