# Generated by Django 4.0.2 on 2022-08-30 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeIdentification', '0003_alter_employeeannouncement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 12, 21, 58, 686071)),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 12, 21, 58, 686071)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 12, 21, 58, 686071)),
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('salarySlip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('taxSheet', models.CharField(max_length=100, unique=True)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
