# Generated by Django 4.0.2 on 2022-12-10 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0004_searchfileupload_alter_employeeannouncement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 20, 13, 28475)),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='AccountName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='AccountNumber',
            field=models.CharField(default='******', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='BankName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='IFSCCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 20, 13, 27473)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 20, 13, 27473)),
        ),
    ]
