# Generated by Django 4.0.2 on 2022-08-28 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0004_rename_relationship_familyemergencycontacts_relationshipname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 16, 44, 769070)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 16, 44, 770088)),
        ),
        migrations.AlterField(
            model_name='familyemergencycontacts',
            name='contactNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
