# Generated by Django 4.0.2 on 2022-08-28 11:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeIdentification', '0005_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 16, 45, 2, 712210)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 16, 45, 2, 712210)),
        ),
        migrations.CreateModel(
            name='Employeequalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualificationType', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], max_length=100)),
                ('Board', models.CharField(max_length=100)),
                ('Year_of_passing', models.CharField(max_length=4)),
                ('certificate_no', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Percentage', models.FloatField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
