# Generated by Django 4.0.2 on 2022-08-31 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0005_alter_employeeannouncement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 13, 6, 29, 12990)),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 13, 6, 29, 11995)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 13, 6, 29, 11995)),
        ),
        migrations.AlterField(
            model_name='employeevisaandpermit',
            name='Citizen',
            field=models.BooleanField(default=False),
        ),
    ]
