# Generated by Django 4.0.2 on 2022-12-10 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0005_alter_employeeannouncement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 24, 50, 568567)),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='AccountNumber',
            field=models.CharField(default='******', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 24, 50, 567568)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 24, 50, 568567)),
        ),
    ]
