# Generated by Django 4.0.2 on 2022-08-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0006_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 16, 53, 36, 951947)),
        ),
        migrations.AlterField(
            model_name='employeequalification',
            name='certificate_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 16, 53, 36, 951947)),
        ),
    ]
