# Generated by Django 4.0.2 on 2022-12-10 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0006_employeebankdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeannouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 44, 32, 40002)),
        ),
        migrations.AlterField(
            model_name='employeecreditleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 44, 32, 40002)),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='DateOfExpire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='DateOfIssue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='PassportNumber',
            field=models.CharField(default='*****', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='PlaceOfIssue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 44, 32, 40002)),
        ),
    ]
