# Generated by Django 4.0.2 on 2022-08-28 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeIdentification', '0007_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 17, 13, 14, 111684)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 17, 13, 14, 111684)),
        ),
        migrations.CreateModel(
            name='Workexperience',
            fields=[
                ('workId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('Management', 'Management'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testing', 'Testing')], max_length=100)),
                ('YearOfExperience', models.FloatField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
