# Generated by Django 4.0.2 on 2022-08-28 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeIdentification', '0011_alter_employeeleavedata_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='AccountNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 17, 41, 34, 268719)),
        ),
        migrations.AlterField(
            model_name='employeetotalleavedata',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 17, 41, 34, 268719)),
        ),
    ]
